{% set name = "cheat" %}
{% set version = "2.1.27" %}
{% set sha256 = "0db3cf8ee3f1a3e5e817d630349f258a08f77bf759c2e9a8025aed481a7739d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - docopt >=0.6.1
    - pygments >=1.6.0

test:
  imports:
    - cheat
    - cheat.cheatsheets
    - cheat.test

about:
  home: https://github.com/chrisallenlane/cheat
  license: MIT/GPL3
  license_file: LICENSE
  summary: 'cheat allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.'
  dev_url: https://github.com/chrisallenlane/cheat

extra:
  recipe-maintainers:
    - proinsias
