travis:
  secure:
    BINSTAR_TOKEN: qb7vvC8B/PIc+dylW15Mmgi3WwGG+nPXZRPlr4vLGDJJMs+eV5Eb6zxDKztRlBQO+JQYgdUelTf+Z0ad/fQ4CK4jhJUTBOYyl7waA8BqiMfPVd4SpF+OGRDW+J/kHhftoSqI+K4LMVbmenq6yZTKuSAOS/B3YHTpJ9mQixmKjih1OuvTd1OxeWkDeHL0XNxrGCf+m6jpGvSHzeTRQAeOPBRzM8Tnk2PjJ1q62UAHlwWX5jifWNeY2x3GvPXhIz9RbszArZCQF6AVslbTHnIrAroG73i97lfqkOXDHdIF3Mh1I1EDjftR+jHIuM6af6dlx5S8YFnD3xwgLm+il2xhqQm2cXyJjeXanxI/Da7rJsmS1Ksq+d7dZr5GWbDhOgQoGmYjmQPe52gcDaDuH9U0E/cKvJw9c4fe0U0/iJRUr/DEHSrHWEPzsZbHnvG38xdy8wBdii6RBJiLni+xeiMf/L4ZJYMkJgQHUUljUHQwwr7zj542MjVrZYkjNrJRLjUj6UCXkhsVZdWIG1dGKy+IPgdKDCHuYu8BFDsMM7x3kXBr/aW17c2+V+yrsn7+38JqY8QgisBOWlEleibgIwP5GyNAqwEL0RlRbfwFWebe2XXhb55ImjnFP2ZXxSmRxWRFqW4CtPM1kzMLZOvbSypYwVv8IVeUrrdWc7WoR/ybRHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
