travis:
  secure:
    BINSTAR_TOKEN: B8oYfeJRn8AYNlKmTG3ux/tf/+GyMWBIP3FPshCqcNKDLIbU4UxL0po8SWbelJln/Zl772eQxG/98H0pM7NSD6Ay3veqzgbQRV1pAzhnP4/5qAnW1KHeWnQOTENg/1rvq9LitPpS6hmqpTZr5jE1C2Z8gSViFvNHePoVaSPZng1br8gROrvSngFktH76DtnohlHz40AguAtMN+6+Nveo3sWFFif7bfO5f3elk7Y9b/Cuiy6WGGNSYGdEL1TzA1h4hwwuRmdoRGlIRBSoJtqbQcBEv1Z84GssNv/3c4spHG0+ycgEG6Jp23AjhiPgbCUdsqBHXnnxuYlB5ofvb9FvXjMa7NF0yBq4bQwfpehmpev8m0ayOszBHPk9OSeSLemh+RQkWMQfDz8oV0WY8W18R1j7JsUpggAst7fpaxWzayxUAjAzfSo1bjFWRKMCofCLH/ld0G7VVCy1sxscJpE7VWrOzz5y4CZQqWhVU/qBxZ9aK4ZsU3e95d2WN6FpRZVvmgTawNwvz3UYYdWP+F73NLy1iqtOyOchwBlNCGvbQ2mK0zSFaHrV4HKA7fmkYvUyu6VSX+lsDMdeQRBTp5CsMwrf4E1EzdsCbz/iB1O0i98brik2Lgq2nWnaNic5bb9v5YZ1+utPCo8Gb9uiOLpIX95h3JMf0DZ7oEZCdM58ir0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
